### ISSUE TITLE
add_custom_target error during catkin_make

### ISSUE THREAD

**Issue by tfinley** [OSUrobotics/palantir_backup#1]
It failed in catkin_make. with 12 errors like this all from targets/programs that I wrote myself are just in devel:

CMake Error at /home/taylor/catkin_ws/build/roskomodo/ros_comm/messages/rosgraph_msgs/cmake/rosgraph_msgs-genmsg.cmake:41 (add_custom_target):
  add_custom_target cannot create target
  "rosgraph_msgs_generate_messages_cpp" because another target with the same
  name already exists.  The existing target is a custom target created in
  source directory "/home/taylor/catkin_ws/src/publish_image".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /opt/ros/hydro/share/genmsg/cmake/genmsg-extras.cmake:299 (include)
  roskomodo/ros_comm/messages/rosgraph_msgs/CMakeLists.txt:11 (generate_messages)

full output here: http://pastebin.com/bKvib7qK

**Comment by curranw** [comment]
I believe this is a hydro bug. Fixed in the hydro branch.
